name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: knitkode/action-content-paths@v0.0.5
      - uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: Content paths update
          branch: ${{ github.head_ref }}
          commit_options: '--no-verify --signoff'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
