name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: knitkode/action-content-paths@v0.0.1
      - uses: stefanzweifel/git-auto-commit-action@v4
